server:
  servlet:
    context-path: /api/v1

spring:
  application.name: autodealer
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./users;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false